### ISSUE TITLE
Model compare failed on a server with FIPS switched on

### ISSUE THREAD

**Issue by elizarovdm** [msallin/SQLiteCodeFirst#133]
We use Sqlite lib in our web api and faced with the following error:
 ERROR GenericHandler [(null)] - System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA512Managed..ctor()
   at SQLite.CodeFirst.Utility.HashCreator.CreateHash(String data)
   at SQLite.CodeFirst.SqliteDropCreateDatabaseWhenModelChanges`1.IsSameModel(TContext context)
   at SQLite.CodeFirst.SqliteDropCreateDatabaseWhenModelChanges`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

The problem is in SHA512Managed which is not supported by FIPS. 
Possible solution is just replace SHA512Managed with SHA512CryptoServiceProvider in HashCreator.CreateHash method.

**Comment by msallin** [comment]
Will not fix this as
a) It is not security relevant which hash algorithm SQLite.CodeFirst uses.
b) It is possible to break existing functionality (generates a different hash than the current function)
