### ISSUE TITLE
UNC paths crash Entity Framework

### ISSUE THREAD

**Issue by CADbloke** [msallin/SQLiteCodeFirst#65]
Some highlights in part of the error message ...
`SQLite error (14): os_win.c:40135: (3) winOpen(C:\CADBLOKE-8560W\CodezOnD\tvCADtest\XXX.tvCADdb) - The system cannot find the path specified.
SQLite error (14): cannot open file at line 40144 of [92dc59fd5a]`

Note the `C:` at the start of the path? The actual path starts with `\\CADBLOKE-8560W\CodezOnD\tvCADtest` but something has re-rooted the path to `C:\`

I think it is due to the rather unique way SQLite does UNC paths as per: http://sqlite.1065341.n5.nabble.com/System-Data-SQLite-and-UNC-Paths-td72920.html
...more info at ...
http://stackoverflow.com/a/18506097/492 and note the comment 
`so with the escaping notation in c# you need to write 8 backslashes: \\\\\\\\network\\share\\file.db`

I wish I knew where to look for that and fix i properly - this would be a  pull-request instead of an issue if I was that clever.

I worked around it with ...

```
string uncString = Regex.Replace(DbPath, @"^\\\\(?!\\)", @"\\\\\\\\",
                        RegexOptions.IgnoreCase | RegexOptions.Singleline);
```

and used `uncString` for `DbPath` in the DbContext constructor, namely ...

```
public TvCadDbContext(string DbPath)
            : base(
                new SQLiteConnection
                {
                    ConnectionString =
                        new SQLiteConnectionStringBuilder {DataSource = DbPath, ForeignKeys = true}.ConnectionString
                }, contextOwnsConnection: true)
        { }
```

the TLDR; error message

```
System.Data.Entity.Core.EntityException was unhandled by user code
  HResult=-2146233087
  Message=The underlying provider failed on Open.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
       at System.Data.Entity.DbContextTransaction.EnsureOpenConnection()
       at System.Data.Entity.DbContextTransaction..ctor(EntityConnection connection)
       at System.Data.Entity.Database.BeginTransaction()
       at SQLite.CodeFirst.SqliteInitializerBase`1.InitializeDatabase(TContext context) in C:\Codez\tvCAD\z.libraries\sqlitecodefirst\sqlite.codefirst\DbInitializers\SqliteInitializerBase.cs:line 76
       at SQLite.CodeFirst.SqliteDropCreateDatabaseWhenModelChanges`1.InitializeDatabase(TContext context) in C:\Codez\tvCAD\z.libraries\sqlitecodefirst\sqlite.codefirst\DbInitializers\SqliteDropCreateDatabaseWhenModelChanges.cs:line 82
       at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
  InnerException: 
       ErrorCode=14
       HResult=-2147467259
       Message=unable to open database file
       Source=System.Data.SQLite
       StackTrace:
            at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
            at System.Data.SQLite.SQLiteConnection.Open()
            at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
            at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
            at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
```

Thanks again for creating and maintaining this project

**Comment by msallin** [comment]
Hi

At a first glance it looks more like an Issue with EF and the Sqlite provider than with "SQLiteCodeFirst".
There are only a few places in this project where I work with the path of the file.

The first one is the [ConnectionStringParser.cs](https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Internal/Utility/ConnectionStringParser.cs), where I get the file path out of the connection string and replace the |DataDirectory| token if its present. The second one is the [SqliteInitializerBase.cs](https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/DbInitializers/SqliteInitializerBase.cs) where I use the ConnectionStringParser the get the path out of the connection string. All further work is done by using the FileInfo class (Create directories if necessary, check if the file exists, delete the file).

The SQLite Development Team takes care for the System.Data.SQLite Lib.
See https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki

Regards Marc

**Comment by CADbloke** [comment]
Thanks Marc, 

I had a feeling that was the case. Thanks for clarifying it for me. I'll chase it up with them & let you know what I find.

cheers
Ewen

**Comment by msallin** [comment]
Any news?

**Comment by CADbloke** [comment]
I didn't chase it up at SQLite, sorry. I use this to fix UNC paths in the property that holds the database `folder` path (minus the file name) ...

``` csharp
string fixforSqliteUncPath = Regex.Replace(folder, @"^\\\\(?!\\)", @"\\\\\\\\",
                        RegexOptions.IgnoreCase | RegexOptions.Singleline);
```

I haven't had any explosions since. If the original cause went away, it should continue to work properly.

**Comment by CADbloke** [comment]
For time travellers ...
https://www.sqlite.org/useovernet.html
https://stackoverflow.com/questions/17303076/sqlite-cannot-open-network-file-programmatically-even-though-worked-before/18506097#18506097
