### ISSUE TITLE
In memory sqlite databases no working

### ISSUE THREAD

**Issue by hugonugra** [msallin/SQLiteCodeFirst#86]
<connectionStrings>
    <add name="default" connectionString="Data Source=:memory:" providerName="System.Data.SQLite" />
</connectionStrings> 

Error:
SQL logic error or missing database no such table: xxx

**Comment by msallin** [comment]
Please provide the details which are necessary to reproduce this issue.

**Comment by samukce** [comment]
@msallin  I guess I have been catching the same issue when I tried to use SQLite in memory following this pass https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite

> SQL logic error or missing database
> no such table: TableName

 ```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
```

**Comment by hugonugra** [comment]
Sorry for the delay.

[InmemorySQLite.zip](https://github.com/msallin/SQLiteCodeFirst/files/984012/InmemorySQLite.zip)

this is the key problem:

public class TestContext : DbContext
    {
        //const string _connectionString = "Data Source=Data\\TestDb.sqlite; Version=3;";  // Ok
        const string _connectionString = "Data Source=:memory:";                           // No Works

        public TestContext() : base(new SQLiteConnection() { ConnectionString = _connectionString }, true)
        {
        }

        public DbSet<Client> Clients { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var sqliteConnectionInitializer = new SqliteCreateDatabaseIfNotExists<TestContext>(modelBuilder);
            Database.SetInitializer(sqliteConnectionInitializer);
        }
    }

**Comment by msallin** [comment]
This is not releated to SQLite.CodeFirst but I assume that you find the solution to your problem in the sample project.

https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst.Console/Program.cs#L26

**Comment by hugonugra** [comment]
Thank you very much
